services:
  app:
    build: .
    restart: always
    depends_on:
      db:
        condition: "service_healthy"
    env_file:
      - .env
    ports:
      - "8000:8000"

  db:
    image: postgres:17
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname=$${POSTGRES_DB} --username=$${POSTRGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dcagatay/pwless-pgadmin4
    depends_on:
      db:
        condition: "service_healthy"
    env_file:
      - .env
    ports:
      - "8001:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 80"]
      start_period: 5s
      interval: 2s
      timeout: 2s
      retries: 15

  test_db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${TEST_POSTGRES_DB}
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
    ports:
      - "${TEST_POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname=$${POSTGRES_DB} --username=$${POSTRGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
