services:
  app:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"

  db:
    image: postgres:17
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname=$${POSTGRES_DB} --username=$${POSTRGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dcagatay/pwless-pgadmin4
    depends_on:
      db:
        condition: "service_healthy"
    env_file:
      - .env
    ports:
      - "8001:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 80"]
      start_period: 5s
      interval: 2s
      timeout: 2s
      retries: 15
