[project]
name = "mpt-finops-operations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi-camelcase>=2.0.0",
    "fastapi[standard]>=0.115.5",
    "pycountry>=24.6.1",
    "pydantic-extra-types>=2.10.0",
]

[dependency-groups]
dev = [
    "bandit>=1.8.0",
    "pytest>=8.3.3",
    "pytest-asyncio>=0.24.0",
    "ruff>=0.8.0",
    "typer>=0.13.1",
]
