import logging

from _pytest.logging import LogCaptureFixture
from httpx import AsyncClient
from pytest_httpx import HTTPXMock

from app import Settings
from app.db.models import Organization
from app.enums import OrganizationStatus
from tests.types import ModelFactory

FAKE_USER_ID = "1bf6f063-d90b-4d45-8e7f-62fefa9f5471"
FAKE_LINKED_ORG_ID = "1bf8f888-d88b-8d88-8e8f-88fefa8f888"


async def test_add_additional_admin_request(
    operations_client: AsyncClient,
    organization_factory: ModelFactory[Organization],
    test_settings: Settings,
    httpx_mock: HTTPXMock,
    caplog: LogCaptureFixture,
):
    organization = await organization_factory(
        name="ACME CO",
        currency="EUR",
        linked_organization_id=FAKE_LINKED_ORG_ID,
    )
    httpx_mock.add_response(
        method="GET",
        url="https://opt-auth.ffc.com/user_existence?email=peter.parker@spiderman.com&user_info=true",
        json={
            "exists": True,
            "user_info": {
                "created_at": 1758810511,
                "deleted_at": 0,
                "id": FAKE_USER_ID,
                "display_name": "Peter Parker",
                "is_active": True,
                "type_id": 1,
                "email": "peter.parker@spiderman.com",
                "verified": True,
                "scope_id": None,
                "slack_connected": False,
                "is_password_autogenerated": False,
                "jira_connected": False,
            },
        },
        match_headers={"Secret": test_settings.optscale_cluster_secret},
    )

    httpx_mock.add_response(
        method="POST",
        headers={"Authorization": operations_client.headers["Authorization"]},
        url=f"{test_settings.optscale_rest_api_base_url}/organizations/{organization.linked_organization_id}/employees",
        status_code=409,
        text="Conflict",
    )
    httpx_mock.add_response(
        method="POST",
        headers={"Authorization": operations_client.headers["Authorization"]},
        url=f"{test_settings.optscale_auth_api_base_url}/users/{FAKE_USER_ID}/assignment_register",
        status_code=201,
    )

    with caplog.at_level(logging.INFO):
        response = await operations_client.post(
            f"/organizations/{organization.id}/add-admin",
            json={
                "email": "peter.parker@spiderman.com",
                "display_name": "Peter Parker",
                "notes": "What a wonderful idea",
            },
        )
        assert response.status_code == 200
        response = response.json()
        assert response["email"] == "peter.parker@spiderman.com"
        assert response["display_name"] == "Peter Parker"
        assert response["id"].startswith("FAAR")
        assert caplog.messages[2] == (
            f"The User Peter Parker (1bf6f063-d90b-4d45-8e7f-62fefa9f5471) "
            f"already belongs to the Organization {FAKE_LINKED_ORG_ID}."
        )


async def test_cannot_add_additional_admin_with_affiliate_account(
    affiliate_client: AsyncClient, organization_factory: ModelFactory[Organization]
):
    organization = await organization_factory(operations_external_id="EXTERNAL_ID_2")
    response = await affiliate_client.post(
        f"/organizations/{organization.id}/add-admin",
        json={
            "email": "peter.parker@spiderman.com",
            "display_name": "Perter Parker",
            "notes": "What a wonderful idea",
        },
    )
    assert response.status_code == 403


async def test_cannot_add_additional_admin_with_no_existing_org(operations_client: AsyncClient):
    organization_id = "FORG-6636-4936-8593"
    response = await operations_client.post(
        f"/organizations/{organization_id}/add-admin",
        json={
            "email": "peter.parker@spiderman.com",
            "display_name": "Perter Parker",
            "notes": "What a wonderful idea",
        },
    )
    assert response.status_code == 404


async def test_cannot_add_additional_admin_with_a_deleted_org(
    operations_client: AsyncClient, organization_factory: ModelFactory[Organization]
):
    organization = await organization_factory(
        name="ACME CO",
        currency="EUR",
        linked_organization_id=FAKE_LINKED_ORG_ID,
        status=OrganizationStatus.DELETED,
    )
    response = await operations_client.post(
        f"/organizations/{organization.id}/add-admin",
        json={
            "email": "peter.parker@spiderman.com",
            "display_name": "Perter Parker",
            "notes": "What a wonderful idea",
        },
    )
    assert response.status_code == 400
    data = response.json()
    assert data["detail"] == "Cannot add administrator: organization ACME CO is deleted."


async def test_add_additional_admin_with_no_existing_user(
    operations_client: AsyncClient,
    organization_factory: ModelFactory[Organization],
    httpx_mock: HTTPXMock,
    test_settings: Settings,
):
    organization = await organization_factory(
        name="ACME CO",
        currency="EUR",
        linked_organization_id=FAKE_LINKED_ORG_ID,
    )

    httpx_mock.add_response(
        method="GET",
        url="https://opt-auth.ffc.com/user_existence?email=peter.parker@spiderman.com&user_info=true",
        json={"exists": False},
        match_headers={"Secret": test_settings.optscale_cluster_secret},
    )
    httpx_mock.add_response(
        method="POST",
        headers={"Authorization": operations_client.headers["Authorization"]},
        url=f"{test_settings.api_modifier_base_url}/users",
        status_code=201,
        json={
            "created_at": 1730126521,
            "deleted_at": 0,
            "id": FAKE_USER_ID,
            "display_name": "Spider Man",
            "is_active": True,
            "type_id": 1,
            "email": "peter.parker@iamspiderman.com",
            "verified": True,
            "scope_id": None,
            "slack_connected": False,
            "is_password_autogenerated": False,
            "jira_connected": False,
            "token": None,
        },
    )

    httpx_mock.add_response(
        method="POST",
        match_headers={"Secret": test_settings.optscale_cluster_secret},
        url=f"{test_settings.optscale_rest_api_base_url}/organizations/{organization.linked_organization_id}/employees",
        match_json={"name": "Peter Parker", "auth_user_id": FAKE_USER_ID},
        status_code=201,
    )

    httpx_mock.add_response(
        method="POST",
        headers={"Authorization": operations_client.headers["Authorization"]},
        url=f"{test_settings.optscale_auth_api_base_url}/users/{FAKE_USER_ID}/assignment_register",
        status_code=201,
    )
    httpx_mock.add_response(
        method="POST",
        url=f"{test_settings.optscale_rest_api_base_url}/restore_password",
        match_json={"email": "peter.parker@spiderman.com"},
        status_code=201,
    )

    response = await operations_client.post(
        f"/organizations/{organization.id}/add-admin",
        json={
            "email": "peter.parker@spiderman.com",
            "display_name": "Peter Parker",
            "notes": "What a wonderful idea",
        },
    )

    assert response.status_code == 200
    response = response.json()
    assert response["email"] == "peter.parker@spiderman.com"
    assert response["display_name"] == "Peter Parker"
    assert response["id"].startswith("FAAR")


# api_modifier.APIModifierClient.create_user Exception
async def test_add_additional_admin_request_error_create_user(
    operations_client: AsyncClient,
    organization_factory: ModelFactory[Organization],
    httpx_mock: HTTPXMock,
    test_settings: Settings,
):
    organization = await organization_factory(
        name="ACME CO",
        currency="EUR",
        linked_organization_id=FAKE_LINKED_ORG_ID,
    )
    httpx_mock.add_response(
        method="GET",
        url="https://opt-auth.ffc.com/user_existence?email=peter.parker@spiderman.com&user_info=true",
        json={"exists": False},
        match_headers={"Secret": test_settings.optscale_cluster_secret},
    )

    httpx_mock.add_response(
        method="POST",
        headers={"Authorization": operations_client.headers["Authorization"]},
        url=f"{test_settings.api_modifier_base_url}/users",
        status_code=403,
    )

    response = await operations_client.post(
        f"/organizations/{organization.id}/add-admin",
        json={
            "email": "peter.parker@spiderman.com",
            "display_name": "Peter Parker",
            "notes": "What a wonderful idea",
        },
    )
    data = response.json()
    assert response.status_code == 502
    assert data["detail"] == "Error checking or creating user in FinOps for Cloud: 403 - ."


# optscale_client.create_org_employee Exception
async def test_add_additional_admin_request_error_in_create_org_employee(
    operations_client: AsyncClient,
    organization_factory: ModelFactory[Organization],
    httpx_mock: HTTPXMock,
    test_settings: Settings,
    caplog,
):
    organization = await organization_factory(
        name="ACME CO",
        currency="EUR",
        linked_organization_id=FAKE_LINKED_ORG_ID,
    )

    httpx_mock.add_response(
        method="GET",
        url="https://opt-auth.ffc.com/user_existence?email=peter.parker@spiderman.com&user_info=true",
        json={
            "exists": True,
            "user_info": {
                "created_at": 1758810511,
                "deleted_at": 0,
                "id": FAKE_USER_ID,
                "display_name": "Peter Parker",
                "is_active": True,
                "type_id": 1,
                "email": "peter.parker@spiderman.com",
                "verified": True,
                "scope_id": None,
                "slack_connected": False,
                "is_password_autogenerated": False,
                "jira_connected": False,
            },
        },
        match_headers={"Secret": test_settings.optscale_cluster_secret},
    )

    httpx_mock.add_response(
        method="POST",
        headers={"Authorization": operations_client.headers["Authorization"]},
        url=f"{test_settings.optscale_rest_api_base_url}/organizations/{organization.linked_organization_id}/employees",
        status_code=403,
        text="Error",
    )

    with caplog.at_level(logging.INFO):
        response = await operations_client.post(
            f"/organizations/{organization.id}/add-admin",
            json={
                "email": "peter.parker@spiderman.com",
                "display_name": "Peter Parker",
                "notes": "What a wonderful idea",
            },
        )
        data = response.json()
        assert response.status_code == 502
        assert data["detail"] == (
            "Error Adding Employee Peter Parker to FinOps for Cloud "
            "Organization ACME CO.: 403 - Error."
        )


# optscale_auth_client.make_user_admin Exception
async def test_add_additional_admin_request_error_in_make_user_admin(
    operations_client: AsyncClient,
    organization_factory: ModelFactory[Organization],
    httpx_mock: HTTPXMock,
    test_settings: Settings,
    caplog,
):
    organization = await organization_factory(
        name="ACME CO",
        currency="EUR",
        linked_organization_id=FAKE_LINKED_ORG_ID,
    )
    httpx_mock.add_response(
        method="GET",
        url="https://opt-auth.ffc.com/user_existence?email=peter.parker@spiderman.com&user_info=true",
        json={
            "exists": True,
            "user_info": {
                "created_at": 1758810511,
                "deleted_at": 0,
                "id": FAKE_USER_ID,
                "display_name": "Peter Parker",
                "is_active": True,
                "type_id": 1,
                "email": "peter.parker@spiderman.com",
                "verified": True,
                "scope_id": None,
                "slack_connected": False,
                "is_password_autogenerated": False,
                "jira_connected": False,
            },
        },
        match_headers={"Secret": test_settings.optscale_cluster_secret},
    )
    httpx_mock.add_response(
        method="POST",
        headers={"Authorization": operations_client.headers["Authorization"]},
        url=f"{test_settings.optscale_rest_api_base_url}/organizations/{organization.linked_organization_id}/employees",
        status_code=409,
        text="Conflict",
    )

    httpx_mock.add_response(
        method="POST",
        headers={"Authorization": operations_client.headers["Authorization"]},
        url=f"{test_settings.optscale_auth_api_base_url}/users/{FAKE_USER_ID}/assignment_register",
        status_code=403,
        text="Error",
    )

    with caplog.at_level(logging.INFO):
        response = await operations_client.post(
            f"/organizations/{organization.id}/add-admin",
            json={
                "email": "peter.parker@spiderman.com",
                "display_name": "Peter Parker",
                "notes": "What a wonderful idea",
            },
        )
        data = response.json()
        assert response.status_code == 502
        assert data["detail"] == (
            "Error Promoting User Peter Parker to Admin in FinOps for Cloud ACME CO.: 403 - Error."
        )


# optscale_client.reset_password Exception
async def test_add_additional_admin_error_in_reset_password(
    operations_client: AsyncClient,
    organization_factory: ModelFactory[Organization],
    httpx_mock: HTTPXMock,
    test_settings: Settings,
    caplog,
):
    organization = await organization_factory(
        name="ACME CO",
        currency="EUR",
        linked_organization_id=FAKE_LINKED_ORG_ID,
    )
    httpx_mock.add_response(
        method="GET",
        url="https://opt-auth.ffc.com/user_existence?email=peter.parker@spiderman.com&user_info=true",
        json={"exists": False},
        match_headers={"Secret": test_settings.optscale_cluster_secret},
    )
    httpx_mock.add_response(
        method="POST",
        headers={"Authorization": operations_client.headers["Authorization"]},
        url=f"{test_settings.api_modifier_base_url}/users",
        status_code=201,
        json={
            "created_at": 1730126521,
            "deleted_at": 0,
            "id": FAKE_USER_ID,
            "display_name": "Spider Man",
            "is_active": True,
            "type_id": 1,
            "email": "peter.parker@iamspiderman.com",
            "verified": True,
            "scope_id": None,
            "slack_connected": False,
            "is_password_autogenerated": False,
            "jira_connected": False,
            "token": None,
        },
    )

    httpx_mock.add_response(
        method="POST",
        match_headers={"Secret": test_settings.optscale_cluster_secret},
        url=f"{test_settings.optscale_rest_api_base_url}/organizations/{organization.linked_organization_id}/employees",
        match_json={"name": "Peter Parker", "auth_user_id": FAKE_USER_ID},
        status_code=201,
    )

    httpx_mock.add_response(
        method="POST",
        headers={"Authorization": operations_client.headers["Authorization"]},
        url=f"{test_settings.optscale_auth_api_base_url}/users/{FAKE_USER_ID}/assignment_register",
        status_code=201,
    )
    httpx_mock.add_response(
        method="POST",
        url=f"{test_settings.optscale_rest_api_base_url}/restore_password",
        match_json={"email": "peter.parker@spiderman.com"},
        status_code=403,
        text="Error",
    )

    response = await operations_client.post(
        f"/organizations/{organization.id}/add-admin",
        json={
            "email": "peter.parker@spiderman.com",
            "display_name": "Peter Parker",
            "notes": "What a wonderful idea",
        },
    )
    assert response.status_code == 502
    data = response.json()
    assert data["detail"] == (
        "Error resetting the password for employee in FinOps for Cloud: 403 - Error."
    )
