"""Phase 2 models

Revision ID: 085245566812
Revises:
Create Date: 2025-02-03 18:14:57.275316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '085245566812'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('type', sa.Enum('user', 'system', name='actortype'), server_default='user', nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actors_id'), 'actors', ['id'], unique=True)
    op.create_index(op.f('ix_actors_type'), 'actors', ['type'], unique=False)
    op.create_table('accounts',
    sa.Column('type', sa.Enum('operations', 'affiliate', name='accounttype'), server_default='affiliate', nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'disabled', 'deleted', name='accountstatus'), server_default='active', nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['actors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=True)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('affiliate_external_id', sa.String(length=255), nullable=False),
    sa.Column('operations_external_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'cancelled', 'deleted', name='organizationstatus'), server_default='active', nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['actors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_affiliate_external_id'), 'organizations', ['affiliate_external_id'], unique=True)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=True)
    op.create_index(op.f('ix_organizations_operations_external_id'), 'organizations', ['operations_external_id'], unique=False)
    op.create_table('entitlements',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('operations_external_id', sa.String(length=255), nullable=True),
    sa.Column('affiliate_external_id', sa.String(length=255), nullable=False),
    sa.Column('datasource_id', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('new', 'active', 'terminated', 'deleted', name='entitlementstatus'), server_default='new', nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redeemed_by_id', sa.String(), nullable=True),
    sa.Column('terminated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminated_by_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['redeemed_by_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['terminated_by_id'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['actors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entitlements_id'), 'entitlements', ['id'], unique=True)
    op.create_table('systems',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('jwt_secret', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'disabled', 'deleted', name='systemstatus'), server_default='active', nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['id'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['actors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_systems_external_id'), 'systems', ['external_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_account_id', sa.String(), nullable=True),
    sa.Column('pwd_reset_token', sa.String(length=255), nullable=True),
    sa.Column('pwd_reset_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'disabled', 'deleted', name='userstatus'), server_default='draft', nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['id'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['last_used_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['actors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts_users',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('invitation_token', sa.String(length=255), nullable=True),
    sa.Column('invitation_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('invited', 'invitation-expired', 'active', 'deleted', name='accountuserstatus'), server_default='invited', nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_users_id'), 'accounts_users', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_users_id'), table_name='accounts_users')
    op.drop_table('accounts_users')
    op.drop_table('users')
    op.drop_index(op.f('ix_systems_external_id'), table_name='systems')
    op.drop_table('systems')
    op.drop_index(op.f('ix_entitlements_id'), table_name='entitlements')
    op.drop_table('entitlements')
    op.drop_index(op.f('ix_organizations_operations_external_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_affiliate_external_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_actors_type'), table_name='actors')
    op.drop_index(op.f('ix_actors_id'), table_name='actors')
    op.drop_table('actors')
    # ### end Alembic commands ###
