"""Remove unneeded audit fields from models

Revision ID: 09b830373981
Revises: 5da9a1a6efaa
Create Date: 2025-03-27 10:15:18.020562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '09b830373981'
down_revision: Union[str, None] = '5da9a1a6efaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_datasource_expenses_created_by_actors', 'datasource_expenses', type_='foreignkey')
    op.drop_constraint('fk_datasource_expenses_updated_by_actors', 'datasource_expenses', type_='foreignkey')
    op.drop_constraint('fk_datasource_expenses_deleted_by_actors', 'datasource_expenses', type_='foreignkey')
    op.drop_column('datasource_expenses', 'updated_by')
    op.drop_column('datasource_expenses', 'created_by')
    op.drop_column('datasource_expenses', 'deleted_by')
    op.drop_constraint('fk_exchange_rates_created_by_actors', 'exchange_rates', type_='foreignkey')
    op.drop_constraint('fk_exchange_rates_updated_by_actors', 'exchange_rates', type_='foreignkey')
    op.drop_constraint('fk_exchange_rates_deleted_by_actors', 'exchange_rates', type_='foreignkey')
    op.drop_column('exchange_rates', 'updated_by')
    op.drop_column('exchange_rates', 'created_by')
    op.drop_column('exchange_rates', 'deleted_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_rates', sa.Column('deleted_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('exchange_rates', sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('exchange_rates', sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_exchange_rates_deleted_by_actors', 'exchange_rates', 'actors', ['deleted_by'], ['id'])
    op.create_foreign_key('fk_exchange_rates_updated_by_actors', 'exchange_rates', 'actors', ['updated_by'], ['id'])
    op.create_foreign_key('fk_exchange_rates_created_by_actors', 'exchange_rates', 'actors', ['created_by'], ['id'])
    op.add_column('datasource_expenses', sa.Column('deleted_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('datasource_expenses', sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('datasource_expenses', sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_datasource_expenses_deleted_by_actors', 'datasource_expenses', 'actors', ['deleted_by'], ['id'])
    op.create_foreign_key('fk_datasource_expenses_updated_by_actors', 'datasource_expenses', 'actors', ['updated_by'], ['id'])
    op.create_foreign_key('fk_datasource_expenses_created_by_actors', 'datasource_expenses', 'actors', ['created_by'], ['id'])
    # ### end Alembic commands ###
