"""Create DatasourceExpense.linked_datasource_id

Revision ID: 0fcca0cf1151
Revises: 7cd884694384
Create Date: 2025-05-07 12:30:00.321343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '0fcca0cf1151'
down_revision: Union[str, None] = '7cd884694384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasource_expenses', sa.Column('linked_datasource_id', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasource_expenses', 'linked_datasource_id')
    # ### end Alembic commands ###
