"""Add azure_blob_name column to ChargesFile

Revision ID: 2d33fc29176b
Revises: 6d2b289e6c92
Create Date: 2025-04-17 15:02:15.798716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '2d33fc29176b'
down_revision: Union[str, None] = '6d2b289e6c92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('azure_blob_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'azure_blob_name')
    # ### end Alembic commands ###
