"""remove unused fields for system, user and accountuser

Revision ID: 4e8e385293da
Revises: 8fdb9f36e41c
Create Date: 2026-03-10 13:52:35.776598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e8e385293da'
down_revision: Union[str, None] = '8fdb9f36e41c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts_users', 'invitation_token_expires_at')
    op.drop_column('accounts_users', 'joined_at')
    op.drop_column('accounts_users', 'invitation_token')
    op.drop_index(op.f('ix_systems_external_id_for_non_deleted'), table_name='systems', postgresql_where="(status <> 'deleted'::systemstatus)")
    op.drop_column('systems', 'jwt_secret')
    op.drop_column('systems', 'external_id')
    op.drop_constraint(op.f('fk_users_last_used_account_id_accounts'), 'users', type_='foreignkey')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'password')
    op.drop_column('users', 'pwd_reset_token_expires_at')
    op.drop_column('users', 'last_used_account_id')
    op.drop_column('users', 'pwd_reset_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pwd_reset_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_used_account_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('pwd_reset_token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_users_last_used_account_id_accounts'), 'users', 'accounts', ['last_used_account_id'], ['id'])
    op.add_column('systems', sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('systems', sa.Column('jwt_secret', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_systems_external_id_for_non_deleted'), 'systems', ['external_id'], unique=True, postgresql_where="(status <> 'deleted'::systemstatus)")
    op.add_column('accounts_users', sa.Column('invitation_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('accounts_users', sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('accounts_users', sa.Column('invitation_token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
