"""organization billing currency

Revision ID: 660df34b13b5
Revises: b55c60f80419
Create Date: 2025-03-05 14:53:31.438053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '660df34b13b5'
down_revision: Union[str, None] = 'b55c60f80419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('billing_currency', sa.String(length=3), nullable=True))
    op.execute("UPDATE organizations SET billing_currency = 'EUR'")
    op.alter_column('organizations', 'billing_currency', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'billing_currency')
    # ### end Alembic commands ###
