"""Add datasource_name column to datasource expenses

Revision ID: 6d2b289e6c92
Revises: 09b830373981
Create Date: 2025-04-03 13:24:15.530918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '6d2b289e6c92'
down_revision: Union[str, None] = '09b830373981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasource_expenses', sa.Column('datasource_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasource_expenses', 'datasource_name')
    # ### end Alembic commands ###
