"""add entitilement ds_type and name

Revision ID: 7fcf1b0ba90d
Revises: c16f32ef558c
Create Date: 2025-02-21 10:59:16.704503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '7fcf1b0ba90d'
down_revision: Union[str, None] = 'c16f32ef558c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entitlements', sa.Column('linked_datasource_type', sa.Enum('aws_cnr', 'azure_cnr', 'azure_tenant', 'gcp_cnr', 'unknown', name='datasourcetype'), nullable=True))
    op.add_column('entitlements', sa.Column('linked_datasource_name', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('operations_external_id', sa.String(length=255), nullable=False))
    op.drop_index('ix_organizations_affiliate_external_id', table_name='organizations')
    op.create_index(op.f('ix_organizations_operations_external_id'), 'organizations', ['operations_external_id'], unique=True)
    op.drop_column('organizations', 'affiliate_external_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('affiliate_external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_organizations_operations_external_id'), table_name='organizations')
    op.create_index('ix_organizations_affiliate_external_id', 'organizations', ['affiliate_external_id'], unique=True)
    op.drop_column('organizations', 'operations_external_id')
    op.drop_column('entitlements', 'linked_datasource_name')
    op.drop_column('entitlements', 'linked_datasource_type')
    # ### end Alembic commands ###
