"""add_entitlement_stats_to_account

Revision ID: 80ece7cdb363
Revises: 196f292f2ea2
Create Date: 2025-03-14 10:30:38.194931

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "80ece7cdb363"
down_revision: Union[str, None] = "196f292f2ea2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("new_entitlements_count", sa.Integer(), nullable=True))
    op.add_column("accounts", sa.Column("active_entitlements_count", sa.Integer(), nullable=True))
    op.add_column(
        "accounts", sa.Column("terminated_entitlements_count", sa.Integer(), nullable=True)
    )
    op.execute("UPDATE accounts SET new_entitlements_count = 0")
    op.execute("UPDATE accounts SET active_entitlements_count = 0")
    op.execute("UPDATE accounts SET terminated_entitlements_count = 0")
    op.alter_column("accounts", "new_entitlements_count", nullable=False)
    op.alter_column("accounts", "active_entitlements_count", nullable=False)
    op.alter_column("accounts", "terminated_entitlements_count", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "terminated_entitlements_count")
    op.drop_column("accounts", "active_entitlements_count")
    op.drop_column("accounts", "new_entitlements_count")
    # ### end Alembic commands ###
