"""Add external_id to actor

Revision ID: 8fdb9f36e41c
Revises: 51d41f5610bd
Create Date: 2026-03-10 12:42:10.620598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '8fdb9f36e41c'
down_revision: Union[str, None] = '51d41f5610bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('external_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actors', 'external_id')
    # ### end Alembic commands ###
