"""system: change unique index to conditional on delete

Revision ID: 9736e8ec11a3
Revises: b34e156283c4
Create Date: 2025-02-17 16:58:27.553515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '9736e8ec11a3'
down_revision: Union[str, None] = 'b34e156283c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_systems_external_id', table_name='systems')
    op.create_index('ix_systems_external_id_for_non_deleted', 'systems', ['external_id'], unique=True, postgresql_where=sa.text("status != 'deleted'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_systems_external_id_for_non_deleted', table_name='systems', postgresql_where=sa.text("status != 'deleted'"))
    op.create_index('ix_systems_external_id', 'systems', ['external_id'], unique=True)
    # ### end Alembic commands ###
