"""organization.operations_external_id - make unique index only for non-deleted

Revision ID: a7badd09ba07
Revises: 7fcf1b0ba90d
Create Date: 2025-02-25 10:45:47.582536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'a7badd09ba07'
down_revision: Union[str, None] = '7fcf1b0ba90d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organizations_operations_external_id', table_name='organizations')
    op.create_index('ix_organizations_operations_external_id_for_non_deleted', 'organizations', ['operations_external_id'], unique=True, postgresql_where=sa.text("status != 'deleted'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organizations_operations_external_id_for_non_deleted', table_name='organizations', postgresql_where=sa.text("status != 'deleted'"))
    op.create_index('ix_organizations_operations_external_id', 'organizations', ['operations_external_id'], unique=True)
    # ### end Alembic commands ###
