"""rename external ids

Revision ID: c16f32ef558c
Revises: 9736e8ec11a3
Create Date: 2025-02-21 08:18:10.507260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'c16f32ef558c'
down_revision: Union[str, None] = '9736e8ec11a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entitlements', sa.Column('linked_datasource_id', sa.String(length=255), nullable=True))
    op.drop_column('entitlements', 'operations_external_id')
    op.add_column('organizations', sa.Column('linked_organization_id', sa.String(length=255), nullable=True))
    op.drop_index('ix_organizations_operations_external_id', table_name='organizations')
    op.create_index(op.f('ix_organizations_linked_organization_id'), 'organizations', ['linked_organization_id'], unique=False)
    op.drop_column('organizations', 'operations_external_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('operations_external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_organizations_linked_organization_id'), table_name='organizations')
    op.create_index('ix_organizations_operations_external_id', 'organizations', ['operations_external_id'], unique=False)
    op.drop_column('organizations', 'linked_organization_id')
    op.add_column('entitlements', sa.Column('operations_external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('entitlements', 'linked_datasource_id')
    # ### end Alembic commands ###
