"""increase_amount_fields

Revision ID: f4b7143100d4
Revises: 3679d9919a68
Create Date: 2025-03-25 17:11:30.253986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'f4b7143100d4'
down_revision: Union[str, None] = '3679d9919a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('datasource_expenses', 'month_expenses',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'amount',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('datasource_expenses', 'month_expenses',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###
