name: Notify Teams on PR Activity

on:
  pull_request:
    types: [opened, edited, reopened, closed, synchronize]

jobs:
  notify-teams:
    runs-on: ubuntu-latest
    steps:
      - name: Send Adaptive Card to Teams
        run: |
          curl -H "Content-Type: application/json" \
               -d @- ${{ secrets.TEAMS_WEBHOOK_URL }} <<EOF
          {
            "type": "message",
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "\$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                  "type": "AdaptiveCard",
                  "version": "1.4",
                  "body": [
                    {
                      "type": "ColumnSet",
                      "columns": [
                        {
                          "type": "Column",
                          "width": "auto",
                          "items": [
                            {
                              "type": "Image",
                              "url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                              "size": "Small",
                              "style": "Person"
                            }
                          ]
                        },
                        {
                          "type": "Column",
                          "width": "stretch",
                          "items": [
                            {
                              "type": "TextBlock",
                              "text": "**Pull Request** | [${{ github.repository }} #${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }})",
                              "wrap": true
                            },
                            {
                              "type": "TextBlock",
                              "text": "**${{ github.event.pull_request.title }}**",
                              "wrap": true,
                              "size": "Medium",
                              "weight": "Bolder"
                            },
                            {
                              "type": "TextBlock",
                              "text": "[${{ github.actor }}](https://github.com/${{ github.actor }}) wants to merge `${{ github.event.pull_request.commits }}` commit(s) from `${{ github.event.pull_request.head.ref }}` into `${{ github.event.pull_request.base.ref }}`",
                              "wrap": true,
                              "spacing": "Small"
                            },
                            {
                              "type": "TextBlock",
                              "text": "${{ github.event.pull_request.changed_files }} files changed",
                              "wrap": true,
                              "spacing": "Small"
                            }
                          ]
                        }
                      ]
                    }
                  ],
                  "actions": [
                    {
                      "type": "Action.OpenUrl",
                      "title": "View pull request",
                      "url": "${{ github.event.pull_request.html_url }}"
                    }
                  ]
                }
              }
            ]
          }
          EOF
