name: PR build and merge

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set up its cache
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project dependancies
        run: uv sync --all-extras --dev

      - name: Create the .env file
        run: cp env.example .env

      - name: Run formatting checks
        run: uv run ruff format --check --diff .

      - name: Run linting
        run: uv run ruff check .

      - name: Run security checks
        run: uv run bandit -c pyproject.toml -r .

      - name: Start the testing DB container
        run: docker compose up test_db -d

      - name: Run tests
        run: uv run pytest

      - name: Stop the testing DB container
        if: always()
        run: docker compose down test_db

      - name: Save code coverage report in the artefacts
        uses: actions/upload-artifact@v4
        if: ${{ !env.ACT }}
        with:
          name: coverage-report
          path: htmlcov
          retention-days: 10

      - name: Generate openapi.json
        run: uv run python -m scripts.generate_openapi_json openapi.json

      - name: Save openapi.json the artefacts
        uses: actions/upload-artifact@v4
        if: ${{ !env.ACT }}
        with:
          name: openapi-spec
          path: openapi.json
          retention-days: 10
